### ISSUE TITLE
Discussion: how much configuration as code?

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/pyrenew-hew#170]
> This is a good question about practice for setting configuration and how much this repo is implementation versus configuration, but imo out of scope for this PR. Will open an issue.

_Originally posted by @dylanhmorris in https://github.com/CDCgov/pyrenew-hew/pull/159#discussion_r1866612233_

**Comment by damonbayer** [comment]
Somewhat separate from the issue of where the configuration lives, but my point with that comment was that the configuration _should_ be reviewed.

**Comment by damonbayer** [comment]
@dylanhmorris We should discuss this prior to https://github.com/CDCgov/pyrenew-hew/issues/218 as different models may require different configurations. Under the current implementation, we do not keep the configuration under version control

**Comment by damonbayer** [comment]
We have resolved that priors/configs should be in version control.

We will add them to the repository and configure a container build so that priors/configs are included last. This will allow the other steps to be cached so that the container build is fast.

Every model run should record which file was used for the priors and git commit id.
